name: Build

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        nim:
          - 0.x
          - 1.x
          - 2.x

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: mingw
      run: make basic

    - name: cl
      run: make basicvc

    - name: dll
      run: make basicdll
