name: Build

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        nim:
          - 0.18.0
          - 1.x
          - 2.x
        os:
          - windows-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: mingw
      run: make basic

    - name: cl
      if: matrix.os == 'windows-latest'
      run: make basicvc

    - name: dll
      if: matrix.os == 'windows-latest'
      run: make basicdll
